SummerSchoolS3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:service}-${self:provider.stage}

SummerSchoolS3BucketPolicy:
  Type: AWS::S3::BucketPolicy
  DependsOn: ServerlessDeploymentBucket
  Properties:
    PolicyDocument:
      Statement:
        - Sid: EnforceHttpsAlways
          Effect: Deny
          Principal: "*"
          Action: "*"
          Resource:
            - "arn:aws:s3:::#{SummerSchoolS3Bucket}"
            - "arn:aws:s3:::#{SummerSchoolS3Bucket}/*"
          Condition:
            Bool:
              aws:SecureTransport: "false"
    Bucket:
      Ref: SummerSchoolS3Bucket