ServerlessDeploymentBucket:
  Type: AWS::S3::Bucket
  Properties:
    LoggingConfiguration:
      DestinationBucketName: "${param:s3LoggingBucket}"
      LogFilePrefix: 's3\${self:provider.stage}-serverlessDeployBucketEngine'

ServerlessDeploymentBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    PolicyDocument:
      Statement:
        - Sid: EnforceHttpsAlways
          Effect: Deny
          Principal: "*"
          Action: "*"
          Resource:
            - "arn:aws:s3:::#{ServerlessDeploymentBucket}"
            - "arn:aws:s3:::#{ServerlessDeploymentBucket}/*"
          Condition:
            Bool:
              aws:SecureTransport: "false"
    Bucket:
      Ref: ServerlessDeploymentBucket
